= Galley

image:https://img.shields.io/github/v/tag/galley-run/galley?include_prereleases&sort=semver&style=flat&label=Latest%20release&color=4F75A3[GitHub Tag]

== About Galley

**Galley** is a developer-friendly **sovereign Platform-as-a-Service (PaaS)**.
It lets you **push code → deploy apps and databases** in minutes — without the complexity of Kubernetes or the risks of the Big Tech.

> Deploy with confidence. Sovereignty, compliancy and GDPR by design.

== Why would you use Galley?

Infrastructure should not be a full-time job for small teams and sole developers.
With Galley, you can focus on **building software**.

- **Sovereignty & GDPR** – Your apps and data can stay in the region of your choice.
- **Simple workflow** – Sign up → Push → Deploy.
- **Predictable costs** – No hidden usage traps.
- **Developer-first** – Lightweight, open-source, fast and easy to adopt.

== Development

To get the application running you need a keystore which I would place in `src/main/resources/`.

You can generate a keystore by running the following command:

[shell]
----
keytool -genseckey -keystore keystore.jceks -storetype JCEKS -storepass "secret" -keyalg HmacSHA256 -keysize 2048 -alias HS256 -keypass "secret"
----

In the root folder you also need to copy `_config.json` into `config.json` and change the variables as you need. Make sure the `jwt.secret` aligns with the secret you've put in when creating the keystore.

=== Running Tests
To run the test-suite:

[shell]
----
./mvnw clean test
----

=== Package the application

To package the application:

[shell]
----
./mvnw clean package
----

=== Jooq Code Generation

To generate Jooq XML Structure from your DB connection:

[shell]
----
./mvwn clean jooq-codegen:generate@jooq-codegen-xml
----

Then generate Jooq Kotlin Classes from that XML file:

[shell]
----
./mvwn clean jooq-codegen:generate@jooq-codegen-xml
----

=== Run the application

To run the application:

[shell]
----
./mvnw clean compile exec:java
----

=== (Only for development)

You can start the app with JVM System Property `-Dapp.env=dev` to enable a smoother development experience.

The following customizations only work in if `app.env` is set to `dev`.

==== Extend Access Token TTL

Add JVM System Property `-Djwt.ttl.access=3600` to extend the TTL seconds of the AccessToken (default: 30s).

Recommendation: Don't customize the TTL access unless really needed.


== Help

Galley is built with Kotlin and upon *Eclipse Vert.x™*, a reactive framework which runs on the JVM.
The frontend is built with Vue.js and Typescript.

* https://vertx.io/docs/[Vert.x Documentation]
* https://stackoverflow.com/questions/tagged/vert.x?sort=newest&pageSize=15[Vert.x Stack Overflow]
* https://groups.google.com/forum/?fromgroups#!forum/vertx[Vert.x User Group]
* https://discord.gg/6ry7aqPWXy[Vert.x Discord]


