name: Design Task
description: Track features or tasks you're planning to implement yourself
title: "[Design]: "
labels: ["🎨 Design", "🧑‍💻 Core Team only"]
body:
  - type: markdown
    attributes:
      value: |
        Plan and track features or tasks you're implementing.

  - type: textarea
    id: goal
    attributes:
      label: Goal
      description: What do you want to accomplish?
      placeholder: Implement authentication system, refactor database layer, etc.
    validations:
      required: true

  - type: textarea
    id: requirements
    attributes:
      label: Requirements
      description: What are the technical requirements and acceptance criteria?
      placeholder: |
        - Must support JWT tokens
        - Need to implement refresh token logic
        - Add rate limiting
    validations:
      required: false

  - type: textarea
    id: tasks
    attributes:
      label: Task Breakdown
      description: Break down the work into smaller tasks
      placeholder: |
        - [ ] Set up authentication routes
        - [ ] Implement JWT token generation
        - [ ] Add token validation middleware
        - [ ] Write tests
        - [ ] Update documentation
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this task?
      options:
        - Low
        - Medium
        - High
        - Critical
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Any additional notes, references, or documentation links
    validations:
      required: false
