export const REGIONS = {
  LATAM: 'latam',
  EU: 'eu',
  USA: 'usa',
  NA: 'na',
  APAC: 'apac',
  AFRICA: 'africa',
} as const

type Region = typeof REGIONS[keyof typeof REGIONS]

export interface Country {
  name: string
  region: Region
}

const countries: Record<string, Country> = {
  nl: { name: 'Netherlands', region: REGIONS.EU },
  be: { name: 'Belgium', region: REGIONS.EU },
  de: { name: 'Germany', region: REGIONS.EU },
  us: { name: 'United States of America', region: REGIONS.USA },
  gb: { name: 'United Kingdom of Great Britain and Northern Ireland', region: REGIONS.EU },
  ca: { name: 'Canada', region: REGIONS.NA },
  af: { name: 'Afghanistan', region: REGIONS.APAC },
  al: { name: 'Albania', region: REGIONS.EU },
  dz: { name: 'Algeria', region: REGIONS.AFRICA },
  as: { name: 'American Samoa', region: REGIONS.APAC },
  ad: { name: 'Andorra', region: REGIONS.EU },
  ao: { name: 'Angola', region: REGIONS.AFRICA },
  ai: { name: 'Anguilla', region: REGIONS.LATAM },
  aq: { name: 'Antarctica', region: REGIONS.APAC },
  ag: { name: 'Antigua and Barbuda', region: REGIONS.LATAM },
  ar: { name: 'Argentina', region: REGIONS.LATAM },
  am: { name: 'Armenia', region: REGIONS.EU },
  aw: { name: 'Aruba', region: REGIONS.LATAM },
  au: { name: 'Australia', region: REGIONS.APAC },
  at: { name: 'Austria', region: REGIONS.EU },
  az: { name: 'Azerbaijan', region: REGIONS.EU },
  bs: { name: 'Bahamas', region: REGIONS.LATAM },
  bh: { name: 'Bahrain', region: REGIONS.APAC },
  bd: { name: 'Bangladesh', region: REGIONS.APAC },
  bb: { name: 'Barbados', region: REGIONS.LATAM },
  by: { name: 'Belarus', region: REGIONS.EU },
  bz: { name: 'Belize', region: REGIONS.LATAM },
  bj: { name: 'Benin', region: REGIONS.AFRICA },
  bm: { name: 'Bermuda', region: REGIONS.NA },
  bt: { name: 'Bhutan', region: REGIONS.APAC },
  bo: { name: 'Bolivia (Plurinational State of)', region: REGIONS.LATAM },
  bq: { name: 'Bonaire, Sint Eustatius and Saba', region: REGIONS.LATAM },
  ba: { name: 'Bosnia and Herzegovina', region: REGIONS.EU },
  bw: { name: 'Botswana', region: REGIONS.AFRICA },
  bv: { name: 'Bouvet Island', region: REGIONS.APAC },
  br: { name: 'Brazil', region: REGIONS.LATAM },
  io: { name: 'British Indian Ocean Territory', region: REGIONS.APAC },
  bn: { name: 'Brunei Darussalam', region: REGIONS.APAC },
  bg: { name: 'Bulgaria', region: REGIONS.EU },
  bf: { name: 'Burkina Faso', region: REGIONS.AFRICA },
  bi: { name: 'Burundi', region: REGIONS.AFRICA },
  cv: { name: 'Cabo Verde', region: REGIONS.AFRICA },
  kh: { name: 'Cambodia', region: REGIONS.APAC },
  cm: { name: 'Cameroon', region: REGIONS.AFRICA },
  ky: { name: 'Cayman Islands', region: REGIONS.LATAM },
  cf: { name: 'Central African Republic', region: REGIONS.AFRICA },
  td: { name: 'Chad', region: REGIONS.AFRICA },
  cl: { name: 'Chile', region: REGIONS.LATAM },
  cn: { name: 'China', region: REGIONS.APAC },
  cx: { name: 'Christmas Island', region: REGIONS.APAC },
  cc: { name: 'Cocos (Keeling) Islands', region: REGIONS.APAC },
  co: { name: 'Colombia', region: REGIONS.LATAM },
  km: { name: 'Comoros', region: REGIONS.AFRICA },
  cd: { name: 'Congo (the Democratic Republic of the)', region: REGIONS.AFRICA },
  cg: { name: 'Congo', region: REGIONS.AFRICA },
  ck: { name: 'Cook Islands', region: REGIONS.APAC },
  cr: { name: 'Costa Rica', region: REGIONS.LATAM },
  hr: { name: 'Croatia', region: REGIONS.EU },
  cu: { name: 'Cuba', region: REGIONS.LATAM },
  cw: { name: 'Curaçao', region: REGIONS.LATAM },
  cy: { name: 'Cyprus', region: REGIONS.EU },
  cz: { name: 'Czechia', region: REGIONS.EU },
  ci: { name: "Côte d'Ivoire", region: REGIONS.AFRICA },
  dk: { name: 'Denmark', region: REGIONS.EU },
  dj: { name: 'Djibouti', region: REGIONS.AFRICA },
  dm: { name: 'Dominica', region: REGIONS.LATAM },
  do: { name: 'Dominican Republic', region: REGIONS.LATAM },
  ec: { name: 'Ecuador', region: REGIONS.LATAM },
  eg: { name: 'Egypt', region: REGIONS.AFRICA },
  sv: { name: 'El Salvador', region: REGIONS.LATAM },
  gq: { name: 'Equatorial Guinea', region: REGIONS.AFRICA },
  er: { name: 'Eritrea', region: REGIONS.AFRICA },
  ee: { name: 'Estonia', region: REGIONS.EU },
  sz: { name: 'Eswatini', region: REGIONS.AFRICA },
  et: { name: 'Ethiopia', region: REGIONS.AFRICA },
  fk: { name: 'Falkland Islands [Malvinas]', region: REGIONS.LATAM },
  fo: { name: 'Faroe Islands', region: REGIONS.EU },
  fj: { name: 'Fiji', region: REGIONS.APAC },
  fi: { name: 'Finland', region: REGIONS.EU },
  fr: { name: 'France', region: REGIONS.EU },
  gf: { name: 'French Guiana', region: REGIONS.LATAM },
  pf: { name: 'French Polynesia', region: REGIONS.APAC },
  tf: { name: 'French Southern Territories', region: REGIONS.APAC },
  ga: { name: 'Gabon', region: REGIONS.AFRICA },
  gm: { name: 'Gambia', region: REGIONS.AFRICA },
  ge: { name: 'Georgia', region: REGIONS.EU },
  gh: { name: 'Ghana', region: REGIONS.AFRICA },
  gi: { name: 'Gibraltar', region: REGIONS.EU },
  gr: { name: 'Greece', region: REGIONS.EU },
  gl: { name: 'Greenland', region: REGIONS.NA },
  gd: { name: 'Grenada', region: REGIONS.LATAM },
  gp: { name: 'Guadeloupe', region: REGIONS.LATAM },
  gu: { name: 'Guam', region: REGIONS.APAC },
  gt: { name: 'Guatemala', region: REGIONS.LATAM },
  gg: { name: 'Guernsey', region: REGIONS.EU },
  gn: { name: 'Guinea', region: REGIONS.AFRICA },
  gw: { name: 'Guinea-Bissau', region: REGIONS.AFRICA },
  gy: { name: 'Guyana', region: REGIONS.LATAM },
  ht: { name: 'Haiti', region: REGIONS.LATAM },
  hm: { name: 'Heard Island and McDonald Islands', region: REGIONS.APAC },
  va: { name: 'Holy See', region: REGIONS.EU },
  hn: { name: 'Honduras', region: REGIONS.LATAM },
  hk: { name: 'Hong Kong', region: REGIONS.APAC },
  hu: { name: 'Hungary', region: REGIONS.EU },
  is: { name: 'Iceland', region: REGIONS.EU },
  in: { name: 'India', region: REGIONS.APAC },
  id: { name: 'Indonesia', region: REGIONS.APAC },
  ir: { name: 'Iran (Islamic Republic of)', region: REGIONS.APAC },
  iq: { name: 'Iraq', region: REGIONS.APAC },
  ie: { name: 'Ireland', region: REGIONS.EU },
  im: { name: 'Isle of Man', region: REGIONS.EU },
  il: { name: 'Israel', region: REGIONS.APAC },
  it: { name: 'Italy', region: REGIONS.EU },
  jm: { name: 'Jamaica', region: REGIONS.LATAM },
  jp: { name: 'Japan', region: REGIONS.APAC },
  je: { name: 'Jersey', region: REGIONS.EU },
  jo: { name: 'Jordan', region: REGIONS.APAC },
  kz: { name: 'Kazakhstan', region: REGIONS.APAC },
  ke: { name: 'Kenya', region: REGIONS.AFRICA },
  ki: { name: 'Kiribati', region: REGIONS.APAC },
  kp: { name: "Korea (the Democratic People's Republic of)", region: REGIONS.APAC },
  kr: { name: 'Korea (the Republic of)', region: REGIONS.APAC },
  kw: { name: 'Kuwait', region: REGIONS.APAC },
  kg: { name: 'Kyrgyzstan', region: REGIONS.APAC },
  la: { name: "Lao People's Democratic Republic", region: REGIONS.APAC },
  lv: { name: 'Latvia', region: REGIONS.EU },
  lb: { name: 'Lebanon', region: REGIONS.APAC },
  ls: { name: 'Lesotho', region: REGIONS.AFRICA },
  lr: { name: 'Liberia', region: REGIONS.AFRICA },
  ly: { name: 'Libya', region: REGIONS.AFRICA },
  li: { name: 'Liechtenstein', region: REGIONS.EU },
  lt: { name: 'Lithuania', region: REGIONS.EU },
  lu: { name: 'Luxembourg', region: REGIONS.EU },
  mo: { name: 'Macao', region: REGIONS.APAC },
  mg: { name: 'Madagascar', region: REGIONS.AFRICA },
  mw: { name: 'Malawi', region: REGIONS.AFRICA },
  my: { name: 'Malaysia', region: REGIONS.APAC },
  mv: { name: 'Maldives', region: REGIONS.APAC },
  ml: { name: 'Mali', region: REGIONS.AFRICA },
  mt: { name: 'Malta', region: REGIONS.EU },
  mh: { name: 'Marshall Islands', region: REGIONS.APAC },
  mq: { name: 'Martinique', region: REGIONS.LATAM },
  mr: { name: 'Mauritania', region: REGIONS.AFRICA },
  mu: { name: 'Mauritius', region: REGIONS.AFRICA },
  yt: { name: 'Mayotte', region: REGIONS.AFRICA },
  mx: { name: 'Mexico', region: REGIONS.LATAM },
  fm: { name: 'Micronesia (Federated States of)', region: REGIONS.APAC },
  md: { name: 'Moldova (the Republic of)', region: REGIONS.EU },
  mc: { name: 'Monaco', region: REGIONS.EU },
  mn: { name: 'Mongolia', region: REGIONS.APAC },
  me: { name: 'Montenegro', region: REGIONS.EU },
  ms: { name: 'Montserrat', region: REGIONS.LATAM },
  ma: { name: 'Morocco', region: REGIONS.AFRICA },
  mz: { name: 'Mozambique', region: REGIONS.AFRICA },
  mm: { name: 'Myanmar', region: REGIONS.APAC },
  na: { name: 'Namibia', region: REGIONS.AFRICA },
  nr: { name: 'Nauru', region: REGIONS.APAC },
  np: { name: 'Nepal', region: REGIONS.APAC },
  nc: { name: 'New Caledonia', region: REGIONS.APAC },
  nz: { name: 'New Zealand', region: REGIONS.APAC },
  ni: { name: 'Nicaragua', region: REGIONS.LATAM },
  ne: { name: 'Niger', region: REGIONS.AFRICA },
  ng: { name: 'Nigeria', region: REGIONS.AFRICA },
  nu: { name: 'Niue', region: REGIONS.APAC },
  nf: { name: 'Norfolk Island', region: REGIONS.APAC },
  mp: { name: 'Northern Mariana Islands', region: REGIONS.APAC },
  no: { name: 'Norway', region: REGIONS.EU },
  om: { name: 'Oman', region: REGIONS.APAC },
  pk: { name: 'Pakistan', region: REGIONS.APAC },
  pw: { name: 'Palau', region: REGIONS.APAC },
  ps: { name: 'Palestine, State of', region: REGIONS.APAC },
  pa: { name: 'Panama', region: REGIONS.LATAM },
  pg: { name: 'Papua New Guinea', region: REGIONS.APAC },
  py: { name: 'Paraguay', region: REGIONS.LATAM },
  pe: { name: 'Peru', region: REGIONS.LATAM },
  ph: { name: 'Philippines', region: REGIONS.APAC },
  pn: { name: 'Pitcairn', region: REGIONS.APAC },
  pl: { name: 'Poland', region: REGIONS.EU },
  pt: { name: 'Portugal', region: REGIONS.EU },
  pr: { name: 'Puerto Rico', region: REGIONS.LATAM },
  qa: { name: 'Qatar', region: REGIONS.APAC },
  mk: { name: 'Republic of North Macedonia', region: REGIONS.EU },
  ro: { name: 'Romania', region: REGIONS.EU },
  ru: { name: 'Russian Federation', region: REGIONS.EU },
  rw: { name: 'Rwanda', region: REGIONS.AFRICA },
  re: { name: 'Réunion', region: REGIONS.AFRICA },
  bl: { name: 'Saint Barthélemy', region: REGIONS.LATAM },
  sh: { name: 'Saint Helena, Ascension and Tristan da Cunha', region: REGIONS.AFRICA },
  kn: { name: 'Saint Kitts and Nevis', region: REGIONS.LATAM },
  lc: { name: 'Saint Lucia', region: REGIONS.LATAM },
  mf: { name: 'Saint Martin (French part)', region: REGIONS.LATAM },
  pm: { name: 'Saint Pierre and Miquelon', region: REGIONS.NA },
  vc: { name: 'Saint Vincent and the Grenadines', region: REGIONS.LATAM },
  ws: { name: 'Samoa', region: REGIONS.APAC },
  sm: { name: 'San Marino', region: REGIONS.EU },
  st: { name: 'Sao Tome and Principe', region: REGIONS.AFRICA },
  sa: { name: 'Saudi Arabia', region: REGIONS.APAC },
  sn: { name: 'Senegal', region: REGIONS.AFRICA },
  rs: { name: 'Serbia', region: REGIONS.EU },
  sc: { name: 'Seychelles', region: REGIONS.AFRICA },
  sl: { name: 'Sierra Leone', region: REGIONS.AFRICA },
  sg: { name: 'Singapore', region: REGIONS.APAC },
  sx: { name: 'Sint Maarten (Dutch part)', region: REGIONS.LATAM },
  sk: { name: 'Slovakia', region: REGIONS.EU },
  si: { name: 'Slovenia', region: REGIONS.EU },
  sb: { name: 'Solomon Islands', region: REGIONS.APAC },
  so: { name: 'Somalia', region: REGIONS.AFRICA },
  za: { name: 'South Africa', region: REGIONS.AFRICA },
  gs: { name: 'South Georgia and the South Sandwich Islands', region: REGIONS.LATAM },
  ss: { name: 'South Sudan', region: REGIONS.AFRICA },
  es: { name: 'Spain', region: REGIONS.EU },
  lk: { name: 'Sri Lanka', region: REGIONS.APAC },
  sd: { name: 'Sudan', region: REGIONS.AFRICA },
  sr: { name: 'Suriname', region: REGIONS.LATAM },
  sj: { name: 'Svalbard and Jan Mayen', region: REGIONS.EU },
  se: { name: 'Sweden', region: REGIONS.EU },
  ch: { name: 'Switzerland', region: REGIONS.EU },
  sy: { name: 'Syrian Arab Republic', region: REGIONS.APAC },
  tw: { name: 'Taiwan', region: REGIONS.APAC },
  tj: { name: 'Tajikistan', region: REGIONS.APAC },
  tz: { name: 'Tanzania, United Republic of', region: REGIONS.AFRICA },
  th: { name: 'Thailand', region: REGIONS.APAC },
  tl: { name: 'Timor-Leste', region: REGIONS.APAC },
  tg: { name: 'Togo', region: REGIONS.AFRICA },
  tk: { name: 'Tokelau', region: REGIONS.APAC },
  to: { name: 'Tonga', region: REGIONS.APAC },
  tt: { name: 'Trinidad and Tobago', region: REGIONS.LATAM },
  tn: { name: 'Tunisia', region: REGIONS.AFRICA },
  tr: { name: 'Turkey', region: REGIONS.EU },
  tm: { name: 'Turkmenistan', region: REGIONS.APAC },
  tc: { name: 'Turks and Caicos Islands', region: REGIONS.LATAM },
  tv: { name: 'Tuvalu', region: REGIONS.APAC },
  ug: { name: 'Uganda', region: REGIONS.AFRICA },
  ua: { name: 'Ukraine', region: REGIONS.EU },
  ae: { name: 'United Arab Emirates', region: REGIONS.APAC },
  um: { name: 'United States Minor Outlying Islands', region: REGIONS.APAC },
  uy: { name: 'Uruguay', region: REGIONS.LATAM },
  uz: { name: 'Uzbekistan', region: REGIONS.APAC },
  vu: { name: 'Vanuatu', region: REGIONS.APAC },
  ve: { name: 'Venezuela (Bolivarian Republic of)', region: REGIONS.LATAM },
  vn: { name: 'Viet Nam', region: REGIONS.APAC },
  vg: { name: 'Virgin Islands (British)', region: REGIONS.LATAM },
  vi: { name: 'Virgin Islands (U.S.)', region: REGIONS.LATAM },
  wf: { name: 'Wallis and Futuna', region: REGIONS.APAC },
  eh: { name: 'Western Sahara', region: REGIONS.AFRICA },
  ye: { name: 'Yemen', region: REGIONS.APAC },
  zm: { name: 'Zambia', region: REGIONS.AFRICA },
  zw: { name: 'Zimbabwe', region: REGIONS.AFRICA },
  ax: { name: 'Åland Islands', region: REGIONS.EU },
}

export default countries
