export default [
  "A2 Hosting",
  "AccuWeb Hosting",
  "Akamai Cloud",
  "Alibaba Cloud",
  "All-Inkl",
  "AlphaVPS",
  "AWS",
  "Amazon Web Services",
  "Antagonist",
  "Argeweb",
  "Aruba Cloud",
  "ArvanCloud",
  "Aspiration Hosting",
  "Atlantic.Net",
  "BelugaCDN",
  "Bigstep",
  "BinaryLane",
  "Bit.nl",
  "BitAccel",
  "BlazingFast",
  "Bluehost",
  "Bunny.net",
  "BuyVM",
  "Byte",
  "Bytemark",
  "Catalyst Cloud",
  "Cherry Servers",
  "Closte",
  "CloudAfrica",
  "CloudCone",
  "Cloudflare",
  "Clouding.io",
  "CloudMatters",
  "CloudSigma",
  "Clustered.net",
  "ConnectingByt.es",
  "Contabo",
  "Crucial",
  "DataPacket",
  "DigitalFyre",
  "DigitalOcean",
  "DigitalPacific",
  "Dogado",
  "DreamHost",
  "EdgeVirt",
  "Equinix Metal",
  "EuroVPS",
  "ExonHost",
  "Fasthosts",
  "Fastly Compute",
  "FiberState",
  "Firebase Hosting",
  "Fly.io",
  "Fornex",
  "Fuga Cloud",
  "G-Core Labs",
  "Glesys",
  "Google Cloud",
  "GreenCloud",
  "GreenCloudVPS",
  "GreenGeeks",
  "Greenhost",
  "HawkHost",
  "Heroku",
  "HetrixTools",
  "Hetzner",
  "Hidora",
  "Hivelocity",
  "Host1Plus",
  "Host4Geeks",
  "HostAfrica",
  "HostArmada",
  "HostBlast",
  "HostDime",
  "Hostens",
  "Hosterio",
  "HostEurope",
  "HostGator",
  "HostHatch",
  "Hostinger",
  "HostKey",
  "HostMantis",
  "HostMarble",
  "Hostnet",
  "HostNoc",
  "Hostomy",
  "HostPapa",
  "HostPulse",
  "Hostry",
  "HostSolutions",
  "HostWinds",
  "Huawei Cloud",
  "Hudson Valley Host",
  "HyperHost",
  "Hypernode",
  "i3D.net",
  "IBM Cloud",
  "Ilait",
  "InMotion Hosting",
  "InterServer",
  "IONOS",
  "ISPCONFIG Cloud",
  "IXP Hosting",
  "Kamatera",
  "KasraHost",
  "King Servers",
  "Kinsta NL",
  "KnownHost",
  "KnownSRV",
  "Koddos",
  "Krypt",
  "Leaseweb",
  "LightNode",
  "Linode",
  "LinxyHost",
  "Liquid Web",
  "LiteServer",
  "LogicWeb",
  "Mammoth Networks",
  "Azure",
  "Microsoft Azure",
  "Mijn.Host",
  "MissHosting",
  "MivoCloud",
  "Myloc",
  "MyRepublic Cloud",
  "Mythic Beasts",
  "Namecheap",
  "NedZone",
  "Neon",
  "Netcup",
  "Netlify",
  "Node4",
  "NTT Communications",
  "One.com Cloud",
  "Oracle Cloud",
  "OVHCloud",
  "Oxide Computer",
  "Oxilion",
  "Packet",
  "Pagely",
  "PhoenixNAP",
  "PlanetScale",
  "Platform.sh",
  "Pressable",
  "ProfitServer",
  "ProISP",
  "Proxhost",
  "Quadranet",
  "RackNerd",
  "Rackspace",
  "Rad Web Hosting",
  "Railway",
  "RamNode",
  "RansomIT",
  "Reg.ru",
  "Register.it",
  "ReliableSite",
  "Render",
  "RoseHosting",
  "RoyalCloud",
  "Sakura Internet",
  "ScalaHosting",
  "Scaleway",
  "Seeweb",
  "Selectel",
  "Servebolt",
  "ServerHub",
  "Serverius",
  "ServerMania",
  "ServerPlan",
  "Servers.com",
  "Serverspace",
  "Shinjiru",
  "ShockByte",
  "ShockHosting",
  "Simply.com",
  "SiteGround",
  "SiteHost",
  "SkySilk Cloud",
  "SmartHost",
  "Snel.com",
  "SQR.NL",
  "SSD Nodes",
  "Storm Internet",
  "Strato",
  "Supabase",
  "SwiftVM",
  "Templ",
  "Tencent Cloud",
  "TeraSwitch",
  "Terrahost",
  "Tilaa",
  "Time4VPS",
  "TransIP",
  "True",
  "TurnKey Internet",
  "UCloud",
  "UKFast",
  "Ukrnames",
  "UltraVPS",
  "UpCloud",
  "Veesp",
  "Vercel",
  "Verpex",
  "Versio",
  "VpsCity",
  "VSYS",
  "Vultr",
  "Wable",
  "Webdock.io",
  "Webgo",
  "WebLine Services",
  "WizzHosting",
  "WP Engine",
  "Yandex Cloud",
  "Yourhosting",
  "Z.com",
];
