apiVersion: v1
kind: Namespace
metadata:
  name: galley
  labels:
    name: galley
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: galley-agent-pdb
  namespace: galley
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: galley-agent
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: galley-agent
  namespace: galley
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: galley-agent-config
  namespace: galley
data:
  GALLEY_AGENT_ID: "b9c670f9-0a1c-49f3-badb-f567870413a9"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: galley-agent-cluster-admin
subjects:
  - kind: ServiceAccount
    name: galley-agent
    namespace: galley
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: galley-agent
  namespace: galley
  labels:
    app: galley-agent
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: galley-agent
  template:
    metadata:
      labels:
        app: galley-agent
    spec:
      serviceAccountName: galley-agent
      hostAliases:
        - ip: "192.168.1.167"
          hostnames:
            - "api.galley.dev"
      containers:
        - name: agent
          image: reg.galley.dev:5999/galley-run/agent:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          env:
            - name: GALLEY_AGENT_ID
              valueFrom:
                configMapKeyRef:
                  name: galley-agent-config
                  key: GALLEY_AGENT_ID
          volumeMounts:
            - name: config
              mountPath: /app/conf.json
              subPath: conf.json
              readOnly: true
          resources:
            requests:
              cpu: "1000m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
      volumes:
        - name: config
          configMap:
            name: galley-agent-config
            items:
              - key: conf.json
                path: conf.json
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
